### ISSUE TITLE
installation error, more readme?

### ISSUE THREAD

**Issue by jianshu93** [LTLA/yaumap#1]
Dear yaumap develop:

see the following error:
Installing package into ‘/opt/homebrew/lib/R/4.1/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘yaumap’ ...
** using staged installation
** libs
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -I"/opt/homebrew/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -I../inst/include  -I'/opt/homebrew/lib/R/4.1/site-library/Rcpp/include' -I"/opt/homebrew/opt/gettext/include" -I"/opt/homebrew/opt/llvm/include" -I"/opt/homebrew/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -Xclang -fopenmp -I"/opt/homebrew/opt/openssl@1.1/include"   -fPIC  -g -O2  -c RcppExports.cpp -o RcppExports.o
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -I"/opt/homebrew/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -I../inst/include  -I'/opt/homebrew/lib/R/4.1/site-library/Rcpp/include' -I"/opt/homebrew/opt/gettext/include" -I"/opt/homebrew/opt/llvm/include" -I"/opt/homebrew/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -Xclang -fopenmp -I"/opt/homebrew/opt/openssl@1.1/include"   -fPIC  -g -O2  -c define_parameters.cpp -o define_parameters.o
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -I"/opt/homebrew/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -I../inst/include  -I'/opt/homebrew/lib/R/4.1/site-library/Rcpp/include' -I"/opt/homebrew/opt/gettext/include" -I"/opt/homebrew/opt/llvm/include" -I"/opt/homebrew/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -Xclang -fopenmp -I"/opt/homebrew/opt/openssl@1.1/include"   -fPIC  -g -O2  -c initialize_from_matrix.cpp -o initialize_from_matrix.o
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -I"/opt/homebrew/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -I../inst/include  -I'/opt/homebrew/lib/R/4.1/site-library/Rcpp/include' -I"/opt/homebrew/opt/gettext/include" -I"/opt/homebrew/opt/llvm/include" -I"/opt/homebrew/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -Xclang -fopenmp -I"/opt/homebrew/opt/openssl@1.1/include"   -fPIC  -g -O2  -c initialize_from_neighbors.cpp -o initialize_from_neighbors.o
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -I"/opt/homebrew/Cellar/r/4.1.2/lib/R/include" -DNDEBUG -I../inst/include  -I'/opt/homebrew/lib/R/4.1/site-library/Rcpp/include' -I"/opt/homebrew/opt/gettext/include" -I"/opt/homebrew/opt/llvm/include" -I"/opt/homebrew/opt/libomp/include" -isysroot "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" -Xclang -fopenmp -I"/opt/homebrew/opt/openssl@1.1/include"   -fPIC  -g -O2  -c run.cpp -o run.o
/opt/homebrew/opt/llvm/bin/clang++ -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/gettext/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -lomp -L/opt/homebrew/opt/openssl@1.1/lib -o yaumap.so RcppExports.o define_parameters.o initialize_from_matrix.o initialize_from_neighbors.o run.o -L/opt/homebrew/Cellar/r/4.1.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /opt/homebrew/lib/R/4.1/site-library/00LOCK-yaumap/00new/yaumap/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘yaumap’ in namespaceExport(ns, exports):
 undefined exports: umap_from_neighbors
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/homebrew/lib/R/4.1/site-library/yaumap’
Warning message:
In install.packages("/Users/jianshuzhao/Github/yaumap", repos = NULL,  :
  installation of package ‘/Users/jianshuzhao/Github/yaumap’ had non-zero exit status

Any idea why

Thanks,

Jianshu

**Comment by LTLA** [comment]
Because I forgot to commit `umap_from_neighbors.cpp`. Oops, fixed.

But in any case, as you'll see from the `DESCRIPTION`, this package really only exists to allow me to test the [**umappp**](https://github.com/LTLA/umappp) C++ library. You're free to use it for real projects, and I'll do my best to fix any problems, but ultimately you may find **uwot** to be a better long-term choice in terms of support and features.

The underlying C++ code is pretty much the same so shouldn't be any performance difference from **uwot**. The only extra feature here is to make animations across UMAP epochs, and to be honest, UMAP animations kinda suck, they're really boring.

**Comment by jianshu93** [comment]
thanks for quick response！I am also using uwot. just curious and want to see how it looks like.

Jianshu
